---@meta

--FindJoint
--FindJoints
--IsJointBroken
--GetJointType
--GetJointOtherShape
--GetJointShapes
--SetJointMotor
--SetJointMotorTarget
--GetJointLimits
--GetJointMovement
--GetJointedBodies
--DetachJointFromShape
--GetRopeNumberOfPoints
--GetRopePointPosition
--GetRopeBounds
--BreakRope