---@meta

--! FindLight
--! FindLights
--! SetLightEnabled
--! SetLightColor
--! SetLightIntensity
--! GetLightTransform
--! GetLightShape
--! IsLightActive
--! IsPointAffectedByLight
--! GetFlashlight
--! SetFlashlight