---@meta

--! ClearKey
--! ListKeys
--! HasKey
--! SetInt
--! GetInt
--! SetFloat
--! GetFloat
--! SetBool
--! GetBool
--! SetString
--! GetString
--! SetColor
--! GetColor
--! GetTranslatedStringByKey
--! HasTranslationByKey
--! LoadLanguageTable
--! GetUserNickname