---@meta

--! LoadSound
--! UnloadSound
--! LoadLoop
--! UnloadLoop
--! SetSoundLoopUser
--! PlaySound
--! PlaySoundForUser
--! StopSound
--! IsSoundPlaying
--! GetSoundProgress
--! SetSoundProgress
--! PlayLoop
--! GetSoundLoopProgress
--! SetSoundLoopProgress
--! PlayMusic
--! StopMusic
--! IsMusicPlaying
--! SetMusicPaused
--! GetMusicProgress
--! SetMusicProgress
--! SetMusicVolume
--! SetMusicLowPass