---@meta

--! FindVehicle
--! FindVehicles
--! GetVehicleTransform
--! GetVehicleExhaustTransforms
--! GetVehicleVitalTransforms
--! GetVehicleBodies
--! GetVehicleBody
--! GetVehicleHealth
--! GetVehicleParams
--! SetVehicleParam
--! GetVehicleDriverPos
--! GetVehicleAvailableSeatPos
--! GetVehicleSteering
--! GetVehicleDrive
--! DriveVehicle
--! GetVehicleLocationWorldTransform
--! GetVehiclePassengerCount
--! SetVehicleHealth